version: '3.8'

services:
  processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../data/collection1:/app/collection1:rw
      - ../models:/app/models:rw
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/models
      - SENTENCE_TRANSFORMERS_HOME=/app/models
      - HF_HOME=/app/models
      - PYTHONUNBUFFERED=1
    # Add restart policy and health check
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import transformers; import sentence_transformers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s